# Generated by Django 4.2.6 on 2023-10-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersmodel',
            old_name='name',
            new_name='username',
        ),
    ]
