# Generated by Django 4.2.6 on 2023-10-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filmsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('action', 'Action'), ('drama', 'Drama'), ('crime', 'Crime'), ('comedy', 'Comedy')], max_length=60)),
                ('rentalfee', models.IntegerField()),
            ],
        ),
    ]
